Repository firedrakeproject/gusto, pull requests merged in 2024-11, with the labels that each got.

#508 Conservative projection
  gusto/core/__init__.py
  gusto/core/configuration.py
  gusto/core/conservative_projection.py
  gusto/equations/prognostic_equations.py
  gusto/recovery/reversible_recovery.py
  gusto/time_discretisation/time_discretisation.py
  gusto/time_discretisation/wrappers.py
  integration-tests/transport/test_tracer_conservative_transport.py
  unit-tests/recovery_tests/test_conservative_recovery.py
  unit-tests/recovery_tests/test_reversible_recovery.py
  unit-tests/test_conservative_projection.py
Labels: enhancement, research problem

#542 Allow reference profiles to be updated
  gusto/core/io.py
  gusto/solvers/linear_solvers.py
  gusto/timestepping/semi_implicit_quasi_newton.py
  gusto/timestepping/timestepper.py
  integration-tests/model/test_checkpointing.py
Labels: enhancement, research problem

#551 Predictors
  examples/shallow_water/williamson_5.py
  gusto/timestepping/semi_implicit_quasi_newton.py
Labels: enhancement

#558 Make linear continuity form correct for varying linearisation
  gusto/equations/common_forms.py
  gusto/equations/shallow_water_equations.py
  gusto/solvers/linear_solvers.py
Labels: enhancement

#570 Update workflow to use node20 instead of node16
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/website.yml
Labels: admin

#576 Remove remove_initial_w
  examples/compressible_euler/mountain_hydrostatic.py
  gusto/initialisation/hydrostatic_initialisation.py
Labels: bug
