Repository firedrakeproject/gusto, pull requests merged in 2024-12, with the labels that each got.

#581 Implement simultaneous transport with SIQN
  gusto/equations/prognostic_equations.py
  gusto/time_discretisation/time_discretisation.py
  gusto/timestepping/semi_implicit_quasi_newton.py
  integration-tests/data/simult_SIQN_order0_chkpt.h5
  integration-tests/data/simult_SIQN_order1_chkpt.h5
  integration-tests/model/test_simultaneous_SIQN.py
Labels: enhancement

#588 Possibly a small typo in readme url?
  README.md
Labels: admin, documentation

#591 Neaten up subcycling options
  examples/compressible_euler/dcmip_3_1_gravity_wave.py
  examples/compressible_euler/skamarock_klemp_nonhydrostatic.py
  examples/shallow_water/thermal_williamson_2.py
  examples/shallow_water/williamson_2.py
  examples/shallow_water/williamson_5.py
  gusto/core/configuration.py
  gusto/time_discretisation/explicit_runge_kutta.py
  gusto/time_discretisation/time_discretisation.py
  integration-tests/transport/test_advective_then_flux.py
  integration-tests/transport/test_subcycling.py
Labels: enhancement, tidying

#544 use correct beta_u in shallow water linear solvers
  gusto/solvers/linear_solvers.py
Labels: tidying, optimisation

#423 Rexi updated
  .github/workflows/build.yml
  gusto/__init__.py
  gusto/complex_proxy/__init__.py
  gusto/complex_proxy/common.py
  gusto/complex_proxy/mixed.py
  gusto/complex_proxy/mixed_impl.py
  gusto/complex_proxy/vector.py
  gusto/complex_proxy/vector_impl.py
  gusto/core/configuration.py
  gusto/core/io.py
  gusto/equations/boussinesq_equations.py
  gusto/rexi/__init__.py
  gusto/rexi/rexi.py
  gusto/rexi/rexi_coefficients.py
  integration-tests/data/linear_sk_rexi_chkpt.h5
  integration-tests/data/linear_sw_wave_rexi_chkpt.h5
  integration-tests/rexi/test_linear_compressible_boussinesq.py
  integration-tests/rexi/test_linear_sw.py
  integration-tests/rexi/test_rexi_approximations.py
  unit-tests/complex_proxy/test_complex_mixed.py
  unit-tests/complex_proxy/test_complex_vector.py
Labels: enhancement, research problem

#590 Add a pyproject.toml
  pyproject.toml
  setup.py
Labels: admin

#573 Thermal sw
  examples/shallow_water/linear_thermal_galewsky_jet.py
  examples/shallow_water/moist_thermal_equivb_gw.py
  examples/shallow_water/moist_thermal_williamson_5.py
  examples/shallow_water/test_shallow_water_examples.py
  examples/shallow_water/thermal_williamson_2.py
  examples/shallow_water/williamson_5.py
  figures/shallow_water/linear_thermal_galewsky_final.png
  figures/shallow_water/linear_thermal_galewsky_initial.png
  figures/shallow_water/moist_thermal_equivb_gw_final.png
  figures/shallow_water/moist_thermal_equivb_gw_initial.png
  gusto/core/configuration.py
  gusto/core/fields.py
  gusto/diagnostics/shallow_water_diagnostics.py
  gusto/equations/prognostic_equations.py
  gusto/equations/shallow_water_equations.py
  gusto/physics/shallow_water_microphysics.py
  gusto/solvers/linear_solvers.py
  integration-tests/data/sw_fplane_chkpt.h5
  integration-tests/equations/test_linear_sw_wave.py
  integration-tests/equations/test_thermal_sw.py
  integration-tests/physics/test_sw_saturation_adjustment.py
  integration-tests/physics/test_terminator_toy.py
  integration-tests/rexi/test_linear_sw.py
  integration-tests/transport/test_zero_limiter.py
  plotting/shallow_water/plot_linear_thermal_galewsky_jet.py
  plotting/shallow_water/plot_moist_thermal_equivb_gravity_wave.py
Labels: enhancement, equation

#599 Limit quadrature degree for terms involving the Exner pressure
  gusto/core/domain.py
  gusto/diagnostics/compressible_euler_diagnostics.py
  gusto/equations/compressible_euler_equations.py
  gusto/initialisation/hydrostatic_initialisation.py
  gusto/physics/boundary_and_turbulence.py
  gusto/physics/microphysics.py
  gusto/solvers/linear_solvers.py
  integration-tests/data/boussinesq_compressible_chkpt.h5
  integration-tests/data/boussinesq_incompressible_chkpt.h5
  integration-tests/data/dry_compressible_chkpt.h5
  integration-tests/data/linear_sw_wave_chkpt.h5
  integration-tests/data/moist_compressible_chkpt.h5
  integration-tests/data/simult_SIQN_order0_chkpt.h5
  integration-tests/data/simult_SIQN_order1_chkpt.h5
Labels: tidying, optimisation

#574 Mixed velocity-vorticity transport
  examples/compressible_euler/unsaturated_bubble.py
  gusto/core/configuration.py
  gusto/core/domain.py
  gusto/spatial_methods/__init__.py
  gusto/spatial_methods/augmentation.py
  gusto/time_discretisation/explicit_runge_kutta.py
  gusto/time_discretisation/implicit_runge_kutta.py
  gusto/time_discretisation/sdc.py
  gusto/time_discretisation/time_discretisation.py
  integration-tests/conftest.py
  integration-tests/data/sw_fplane_chkpt.h5
  integration-tests/equations/test_sw_fplane.py
  integration-tests/transport/test_vector_recovered_space.py
  integration-tests/transport/test_vorticity_transport.py
Labels: enhancement, equation

#600 add cumulative sum diagnostic
  gusto/diagnostics/diagnostics.py
  unit-tests/diagnostic_tests/test_cumulative_sum.py
Labels: enhancement

#569 Prevent unnecessary refactorisations when matrices haven't changed
  gusto/core/function_spaces.py
  gusto/diagnostics/compressible_euler_diagnostics.py
  gusto/diagnostics/diagnostics.py
  gusto/diagnostics/shallow_water_diagnostics.py
  gusto/solvers/__init__.py
  gusto/solvers/linear_solvers.py
  gusto/solvers/parameters.py
  gusto/time_discretisation/time_discretisation.py
  gusto/time_discretisation/wrappers.py
  gusto/timestepping/semi_implicit_quasi_newton.py
  integration-tests/data/boussinesq_compressible_chkpt.h5
  integration-tests/data/boussinesq_incompressible_chkpt.h5
  integration-tests/data/dry_compressible_chkpt.h5
  integration-tests/data/linear_sw_wave_chkpt.h5
  integration-tests/data/moist_compressible_chkpt.h5
  integration-tests/data/simult_SIQN_order0_chkpt.h5
  integration-tests/data/simult_SIQN_order1_chkpt.h5
  integration-tests/data/sw_fplane_chkpt.h5
  unit-tests/test_function_spaces.py
Labels: optimisation

#540 Relaxation physics
  gusto/core/configuration.py
  gusto/physics/__init__.py
  gusto/physics/held_suarez_forcing.py
  integration-tests/physics/test_held_suarez_friction.py
  integration-tests/physics/test_held_suarez_relaxation.py
Labels: enhancement, research problem

#603 Dolci/fix interpolate warnings
  gusto/diagnostics/diagnostics.py
  gusto/diagnostics/shallow_water_diagnostics.py
  gusto/physics/microphysics.py
  gusto/physics/physics_parametrisation.py
  gusto/physics/shallow_water_microphysics.py
  gusto/recovery/recovery.py
  gusto/recovery/reversible_recovery.py
  gusto/solvers/linear_solvers.py
  gusto/time_discretisation/wrappers.py
  gusto/timestepping/semi_implicit_quasi_newton.py
Labels: enhancement
