Repository firedrakeproject/gusto, pull requests merged in 2024-09, with the labels that each got.

#537 Split timestepper
  gusto/equations/shallow_water_equations.py
  gusto/timestepping/split_timestepper.py
  integration-tests/equations/test_boussinesq.py
  integration-tests/model/test_split_timestepper.py
Labels: enhancement

#548 Fixes to some recovery related issues
  gusto/recovery/recovery_options.py
  gusto/time_discretisation/imex_runge_kutta.py
  gusto/time_discretisation/implicit_runge_kutta.py
  gusto/time_discretisation/time_discretisation.py
  gusto/time_discretisation/wrappers.py
Labels: bug, enhancement

#552 Add missing plotting scripts
  plotting/compressible_euler/plot_dcmip_3_1_gravity_wave.py
  plotting/shallow_water/plot_linear_williamson_2.py
  plotting/shallow_water/plot_moist_convective_williamson_2.py
  plotting/shallow_water/plot_moist_thermal_williamson_5.py
  plotting/shallow_water/plot_shallow_water_1d_wave.py
  plotting/shallow_water/plot_thermal_williamson_2.py
  plotting/shallow_water/plot_williamson_2.py
  plotting/shallow_water/plot_williamson_5.py
Labels: tidying
