Repository firedrakeproject/gusto, pull requests merged in 2024-08, with the labels that each got.

#524 Mixed order recovery
  examples/compressible/dry_bryan_fritsch.py
  examples/compressible/unsaturated_bubble.py
  gusto/recovery/__init__.py
  gusto/recovery/recovery_options.py
  unit-tests/recovery_tests/test_mixed_spaces.py
Labels: enhancement, tidying

#534 Fix mountain initial conditions
  examples/compressible/mountain_hydrostatic.py
Labels: bug

#535 Please don't read me
  README.md
Labels: admin

#533 Reorganise prescribed transport
  gusto/timestepping/split_timestepper.py
  gusto/timestepping/timestepper.py
  integration-tests/equations/test_advection_diffusion.py
  integration-tests/equations/test_coupled_transport.py
  integration-tests/equations/test_forced_advection.py
  integration-tests/model/test_IMEX.py
  integration-tests/model/test_conservative_transport_with_physics.py
  integration-tests/model/test_nc_outputting.py
  integration-tests/model/test_prescribed_transport.py
  integration-tests/model/test_sdc.py
  integration-tests/model/test_time_discretisation.py
  integration-tests/physics/test_precipitation.py
  integration-tests/physics/test_source_sink.py
  integration-tests/physics/test_terminator_toy.py
  integration-tests/transport/test_dg_transport.py
  integration-tests/transport/test_embedded_dg_advection.py
  integration-tests/transport/test_limiters.py
  integration-tests/transport/test_mixed_fs_options.py
  integration-tests/transport/test_recovered_transport.py
  integration-tests/transport/test_subcycling.py
  integration-tests/transport/test_supg_transport.py
  integration-tests/transport/test_vector_recovered_space.py
Labels: enhancement

#536 Solver Convergence Improvements
  gusto/solvers/linear_solvers.py
  gusto/timestepping/semi_implicit_quasi_newton.py
Labels: enhancement, research problem

#539 Coriolis linear solver
  gusto/solvers/linear_solvers.py
Labels: enhancement, research problem

#545 Conservative transport integration test
  gusto/core/configuration.py
  gusto/equations/prognostic_equations.py
  gusto/time_discretisation/wrappers.py
  integration-tests/transport/test_conservative_transport.py
Labels: enhancement
