Repository firedrakeproject/gusto, pull requests merged in 2024-10, with the labels that each got.

#553 Advective-then-Flux form for Runge-Kutta schemes
  examples/compressible_euler/skamarock_klemp_nonhydrostatic.py
  examples/shallow_water/williamson_5.py
  gusto/core/labels.py
  gusto/spatial_methods/transport_methods.py
  gusto/time_discretisation/explicit_runge_kutta.py
  gusto/time_discretisation/time_discretisation.py
  gusto/timestepping/timestepper.py
  integration-tests/equations/test_coupled_transport.py
  integration-tests/model/test_conservative_transport_with_physics.py
  integration-tests/model/test_time_discretisation.py
  integration-tests/transport/test_advective_then_flux.py
  integration-tests/transport/test_dg_transport.py
Labels: enhancement, research problem

#567 Improve clarity of SWSaturationAdjustment class
  gusto/physics/shallow_water_microphysics.py
Labels: tidying

#560 Time Discretisation Improvements
  gusto/core/labels.py
  gusto/equations/prognostic_equations.py
  gusto/time_discretisation/explicit_runge_kutta.py
  gusto/time_discretisation/imex_runge_kutta.py
  gusto/time_discretisation/implicit_runge_kutta.py
  gusto/time_discretisation/multi_level_schemes.py
  gusto/time_discretisation/sdc.py
  gusto/time_discretisation/time_discretisation.py
Labels: bug, enhancement
