Repository firedrakeproject/gusto, pull requests merged in 2025-02, with the labels that each got.

#610 Fix Courant number calculation
  gusto/diagnostics/diagnostics.py
Labels: bug, external issue

#612 Some logging and reduce a quadrature degree
  gusto/timestepping/timestepper.py
Labels: enhancement

#583 Reorganise "hydrostatic" vertical slice tests
  examples/compressible_euler/schaer_mountain.py
  examples/compressible_euler/skamarock_klemp_hydrostatic.py
  examples/compressible_euler/skamarock_klemp_nonhydrostatic.py
  examples/compressible_euler/test_compressible_euler_examples.py
  figures/compressible_euler/schaer_mountain_final.png
  figures/compressible_euler/schaer_mountain_initial.png
  figures/compressible_euler/skamarock_klemp_nonhydrostatic_final.png
  gusto/solvers/linear_solvers.py
  gusto/solvers/parameters.py
  gusto/time_discretisation/time_discretisation.py
  gusto/timestepping/semi_implicit_quasi_newton.py
  plotting/compressible_euler/plot_schaer_mountain.py
  plotting/compressible_euler/plot_skamarock_klemp_nonhydrostatic.py
Labels: tidying, example, figure, plotting script

#596 Parallel netcdf
  .github/workflows/build.yml
  docs/about_gusto.md
  gusto/core/coordinates.py
  gusto/core/domain.py
  gusto/core/io.py
  integration-tests/model/test_nc_outputting.py
Labels: parallel, admin, optimisation

#578 Non-split physics for all explicit or IMEX time discretisations
  gusto/core/labels.py
  gusto/physics/boundary_and_turbulence.py
  gusto/physics/chemistry.py
  gusto/physics/microphysics.py
  gusto/physics/physics_parametrisation.py
  gusto/physics/shallow_water_microphysics.py
  gusto/time_discretisation/explicit_runge_kutta.py
  gusto/time_discretisation/imex_runge_kutta.py
  gusto/time_discretisation/implicit_runge_kutta.py
  gusto/time_discretisation/multi_level_schemes.py
  gusto/time_discretisation/sdc.py
  integration-tests/model/test_nonsplit_physics.py
  integration-tests/physics/test_instant_rain.py
  integration-tests/physics/test_saturation_adjustment.py
  integration-tests/physics/test_source_sink.py
  integration-tests/physics/test_suppress_vertical_wind.py
  integration-tests/physics/test_surface_fluxes.py
  integration-tests/physics/test_sw_saturation_adjustment.py
  integration-tests/physics/test_terminator_toy.py
  integration-tests/physics/test_wind_drag.py
Labels: enhancement, research problem

#614 Copy active tracers in SIQN
  gusto/timestepping/semi_implicit_quasi_newton.py
Labels: bug

#615 purge `Function.split`
  examples/shallow_water/moist_convective_williamson_2.py
  examples/shallow_water/moist_thermal_williamson_5.py
  integration-tests/model/test_nonsplit_physics.py
  integration-tests/transport/test_zero_limiter.py
Labels: external issue

#617 Fix package discovery
  pyproject.toml
Labels: bug, admin
